services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./videos:/app/videos
      - ./predictions:/app/predictions
      - ./reports:/app/reports
      - ./debug_frames:/app/debug_frames
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '6G'
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_CJS_IGNORE_WARNING=true
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge