version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - ./videos:/app/videos
      - ./logs:/app/logs
      - ./reports:/app/reports
      - ./predictions:/app/predictions
      - ./debug_frames:/app/debug_frames
      - ./cache:/app/cache
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge